import * as fs from "fs";
import { glob } from "glob";
import kleur from "kleur";

// Scoped npm package names such as "@tiptap/starter-kit" contain the placeholder but belong to a
// third-party package. Renaming them breaks dependency resolution, so they are matched first and
// kept as-is, while every other occurrence of the placeholder is renamed.
const scopedPackageName = /@[a-z0-9~][a-z0-9._-]*\/[a-z0-9._-]+/;
const placeholder = /[Ss]tarter/;
const placeholderOutsidePackageNames = new RegExp(`${scopedPackageName.source}|${placeholder.source}`, "g");

function replacePlaceholderInContents(contents: string, projectName: string): string {
    return contents.replace(placeholderOutsidePackageNames, (match) => (match.startsWith("@") ? match : projectName));
}

export function replacePlaceholder(projectName: string, verbose: boolean): void {
    const files: string[] = glob.sync([`./**`, `./.*`, `./.**/**`, `./**/.**/**`], {
        maxDepth: 5,
        // Never rewrite lock files or installed dependencies: they are machine-generated and contain
        // third-party package names (e.g. "@tiptap/starter-kit") and download URLs (e.g.
        // ".../starter-kit-3.27.3.tgz") that must not be renamed. Lock files are regenerated by
        // `npm install` during install.sh, so the project name in them is reconciled anyway.
        ignore: [`./.git/**`, `**/node_modules/**`, `**/package-lock.json`],
    });
    let changedFiles = 0;

    files.forEach((file) => {
        try {
            if (!fs.lstatSync(file).isFile()) {
                return;
            }
            const contents = fs.readFileSync(file, "utf8").toString();
            // intl-update.sh also clones the Comet Starter language repository, which keeps its name.
            const newContents = file.endsWith("intl-update.sh")
                ? contents.replaceAll("lang/starter-lang", `lang/${projectName}-lang`)
                : replacePlaceholderInContents(contents, projectName);

            if (newContents !== contents) {
                fs.writeFileSync(file, newContents);
                changedFiles++;
                if (verbose) {
                    console.log(kleur.grey(`Replaced content in ${file}`));
                }
            }
        } catch (e) {
            console.log(kleur.yellow(`Could not replace placeholder in ${file}`));
            if (verbose) {
                console.log(kleur.grey(`${e}`));
            }
        }
    });
    if (verbose) {
        console.log(kleur.grey(`Successfully replaced content in ${changedFiles} files`));
    }
}
