addAssignees: author

addReviewers: true

useReviewGroups: true

reviewGroups:
  default:
    - dkarnutsch
    - fraxachun
    - johnnyomair
    - nsams
    - thomasdax98
    - manuelblum
  dependencyUpdates:
    - johnnyomair
    - thomasdax98
    - manuelblum

useAssigneeGroups: false

skipKeywords:
  - Merge main into next
