addAssignees: author

addReviewers: true

reviewers:
  - dkarnutsch
  - fraxachun
  - johnnyomair
  - nsams
  - thomasdax98
  - manuelblum

skipKeywords:
  - Merge main into next

skipUsers:
  - renovate[bot]
