version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    versioning-strategy: "lockfile-only"
    groups:
      non-major-versions:
        update-types:
          - "minor"
          - "patch"
    assignees:
      - "johnnyomair"

  - package-ecosystem: "npm"
    directory: "/admin"
    schedule:
      interval: "monthly"
    versioning-strategy: "lockfile-only"
    groups:
      non-major-versions:
        update-types:
          - "minor"
          - "patch"
    assignees:
      - "johnnyomair"

  - package-ecosystem: "npm"
    directory: "/admin/server"
    schedule:
      interval: "monthly"
    versioning-strategy: "lockfile-only"
    groups:
      non-major-versions:
        update-types:
          - "minor"
          - "patch"
    assignees:
      - "johnnyomair"

  - package-ecosystem: "npm"
    directory: "/api"
    schedule:
      interval: "monthly"
    versioning-strategy: "lockfile-only"
    groups:
      non-major-versions:
        update-types:
          - "minor"
          - "patch"
    assignees:
      - "johnnyomair"

  - package-ecosystem: "npm"
    directory: "/site"
    schedule:
      interval: "monthly"
    versioning-strategy: "lockfile-only"
    groups:
      non-major-versions:
        update-types:
          - "minor"
          - "patch"
    assignees:
      - "johnnyomair"

  - package-ecosystem: "npm"
    directory: "/create-app"
    schedule:
      interval: "monthly"
    versioning-strategy: "lockfile-only"
    groups:
      non-major-versions:
        update-types:
          - "minor"
          - "patch"
    assignees:
      - "johnnyomair"
