services:
  api:
    build:
      context: api
      dockerfile: Dockerfile
      additional_contexts:
        - site-configs=./site-configs

  admin:
    build:
      context: admin
      dockerfile: Dockerfile
      additional_contexts:
        - api=./api

  site:
    build:
      context: site
      dockerfile: Dockerfile
      additional_contexts:
        - api=./api
        - site-configs=./site-configs
