module.exports = {
    "admin/src/**/*.{ts,tsx,js,jsx,json,css,md}": () => ["npm --prefix admin run lint:eslint", "npm --prefix admin run lint:knip"],
    "admin/**/*.{ts,tsx}": () => "npm --prefix admin run lint:tsc",
    "admin/**/*.{js,json,md,yml,yaml}": () => "npm --prefix admin run lint:prettier",
    "api/src/**/*.{ts,tsx,js,jsx,json,css,md}": () => ["npm --prefix api run lint:eslint", "npm --prefix api run lint:knip"],
    "api/**/*.{ts,tsx}": () => "npm --prefix api run lint:tsc",
    "api/**/*.{js,json,md,yml,yaml}": () => "npm --prefix api run lint:prettier",
    "site/src/**/*.{ts,tsx,js,jsx,json,css,scss,md}": () => ["npm --prefix site run lint:eslint", "npm --prefix site run lint:knip"],
    "site/**/*.{ts,tsx}": () => "npm --prefix site run lint:tsc",
    "site/**/*.{js,json,md,yml,yaml}": () => "npm --prefix site run lint:prettier",
    "site/src/**/*.{ts,tsx,css}": () => "npm --prefix site run lint:style",
    "create-app/src/**/*.{ts,tsx,js,jsx,json,css,scss,md}": () => "npm --prefix create-app run lint:eslint",
    "create-app/**/*.{ts,tsx}": () => "npm --prefix create-app run lint:tsc",
    "create-app/**/*.{js,json,md,yml,yaml}": () => "npm --prefix create-app run lint:prettier",
    "./**/*.{js,json,md,yml,yaml}": () => "npm run lint:root",
};
