module.exports = {
    "admin/src/**/*.{ts,tsx,js,jsx,json,css,md}": () => ["pnpm --dir admin run lint:eslint", "pnpm --dir admin run lint:knip"],
    "admin/**/*.{ts,tsx}": () => ["pnpm --dir admin run lint:tsc", "pnpm --dir admin run intl:extract"],
    "admin/*.{ts,js,json,md,yml,yaml}": () => "pnpm --dir admin run lint:prettier",
    "api/src/**/*.{ts,tsx,js,jsx,json,css,md}": () => ["pnpm --dir api run lint:eslint", "pnpm --dir api run lint:knip"],
    "api/**/*.{ts,tsx}": () => "pnpm --dir api run lint:tsc",
    "api/*.{ts,js,json,md,yml,yaml}": () => "pnpm --dir api run lint:prettier",
    "site/src/**/*.{ts,tsx,js,jsx,json,css,md}": () => ["pnpm --dir site run lint:eslint", "pnpm --dir site run lint:knip"],
    "site/**/*.{ts,tsx}": () => ["pnpm --dir site run lint:tsc", "pnpm --dir site run intl:extract"],
    "site/*.{ts,js,json,md,yml,yaml}": () => "pnpm --dir site run lint:prettier",
    "site/src/**/*.{css,scss}": () => "pnpm --dir site run lint:style",
    "create-app/src/**/*.{ts,tsx,js,jsx,json,css,scss,md}": () => "pnpm --dir create-app run lint:eslint",
    "create-app/**/*.{ts,tsx}": () => "pnpm --dir create-app run lint:tsc",
    "create-app/*.{ts,js,json,md,yml,yaml}": () => "pnpm --dir create-app run lint:prettier",
    "./**/*.{js,json,md,yml,yaml}": () => "pnpm run lint:root",
};
