name: "Copilot Setup Steps"

# Automatically run the setup steps when they are changed to allow for easy validation, and
# allow manual testing through the repository's "Actions" tab
on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/copilot-setup-steps.yml
  pull_request:
    paths:
      - .github/workflows/copilot-setup-steps.yml

jobs:
  # The job MUST be called `copilot-setup-steps` or it will not be picked up by Copilot.
  copilot-setup-steps:
    runs-on: ubuntu-latest

    # Set the permissions to the lowest permissions possible needed for your steps.
    # Copilot will be given its own token for its operations.
    permissions:
      # If you want to clone the repository as part of your setup steps, for example to install dependencies, you'll need the `contents: read` permission. If you don't clone the repository in your setup steps, Copilot will do this for you automatically after the steps complete.
      contents: read

    # You can define any steps you want, and they will run before the agent starts.
    # If you do not check out your code, Copilot will do this for you.
    steps:
      - uses: actions/checkout@v7
        with:
          ref: ${{ github.event.pull_request.head.ref || github.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Use Node.js 24.x
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: "pnpm"
          cache-dependency-path: "**/pnpm-lock.yaml"
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile & pnpm --dir api install --frozen-lockfile & pnpm --dir admin install --frozen-lockfile & pnpm --dir site install --frozen-lockfile & wait
        env:
          NPM_CONFIG_STRICT_PEER_DEPENDENCIES: true

      - name: Setup project for CI run
        run: pnpm run setup:ci && pnpm --dir admin run setup:ci && pnpm --dir site run setup:ci

      - name: Install agent skills
        run: pnpm run install-agent-skills
