name: Publish @comet/create-app

on:
  pull_request:
    types:
      - closed
    branches:
      - main
    paths:
      - create-app/**
  workflow_dispatch:

jobs:
  publish:
    name: Publish @comet/create-app
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ github.actor }}"

      - uses: actions/checkout@v5
        with:
          token: ${{ secrets.VIVID_PLANET_BOT_TOKEN }}
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Use Node.js 22.x
        uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: "npm"
          cache-dependency-path: "create-app/package-lock.json"
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: npm ci --strict-peer-deps
        working-directory: create-app/

      - name: Build
        run: npm run build
        working-directory: create-app/

      - name: Bump version
        run: echo "NEW_VERSION=$(npm --no-git-tag-version version minor)" >> $GITHUB_ENV
        working-directory: create-app/

      - name: Commit package.json
        uses: EndBug/add-and-commit@v9
        with:
          message: "@comet/create-app: Publish ${{ env.NEW_VERSION }}"

      - name: Publish release
        run: npm publish
        working-directory: create-app/
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
