name: Publish @comet/create-app

on:
  pull_request:
    types:
      - closed
    branches:
      - main
    paths:
      - create-app/**
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish:
    name: Publish @comet/create-app
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ github.actor }}"

      - uses: actions/checkout@v7
        with:
          token: ${{ secrets.VIVID_PLANET_BOT_TOKEN }}
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Use Node.js 24.x
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: "pnpm"
          cache-dependency-path: "create-app/pnpm-lock.yaml"
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        working-directory: create-app/
        env:
          NPM_CONFIG_STRICT_PEER_DEPENDENCIES: true

      - name: Build
        run: pnpm run build
        working-directory: create-app/

      - name: Bump version
        run: echo "NEW_VERSION=$(pnpm version minor --no-git-tag-version)" >> $GITHUB_ENV
        working-directory: create-app/

      - name: Commit package.json
        uses: EndBug/add-and-commit@v10
        with:
          message: "@comet/create-app: Publish ${{ env.NEW_VERSION }}"

      - name: Publish release
        run: pnpm publish --no-git-checks
        working-directory: create-app/
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
